### ISSUE TITLE
Simulator orbit is not drawn

### ISSUE THREAD

**Issue by lgeretti** [ariadne-cps/ariadne#365]
It seems that the result from simulation is not drawn, resulting in an empty image file. This can be seen by running the (modified) hybrid evolution tutorial in the provided `hybrid-simulator_drawing#365` branch, which also shows the evolver result drawn as expected.

If you prefer, you can also use the `evolution-tutorial#360` branch, in which the watertank example is used instead and it is also possible to show the trace of simulation. However, I preferred to make the issue branch from the working branch since I am touching stuff around. 

As soon as you fix the issue, I'll merge the commits into the #360 branch myself.

**Comment by pietercollins** [comment]
I've fixed this; the system was taking the "must_switch_on" invariant and treating the progress condition as a guard, which was always activated. 
I think this bug came about partly as a matter of definitions; we should be clear about terminology. In particular, and invariant has an "event" code and a "guard" condition, but does not induce a transition.

**Comment by lgeretti** [comment]
Wait, I already fixed the issue you mentioned in my branch. The problem is independent of that.

**Comment by lgeretti** [comment]
If you want another example, you could try this project of one of our students: https://github.com/antonellocontini/boat-ariadne/tree/master/src
In that example I noticed that only the plots for algebraic variables are not shown. However, in the watertank example also the differential variables have this problem.

**Comment by lgeretti** [comment]
See evolution-tutorial#360 for the issue.

**Comment by lgeretti** [comment]
Very strangely, today the same example shows the time-height plot correctly. What is missing from the aperture-height plot is related to the locations where aperture is algebraic. It does not depend on aperture being constant, since I tried with a small time-dependent perturbation (+height/100) and it is still not plotted.
